import os


# SERVICE CONFIGURATION

HOST = os.getenv('AUTH_SERVICE_HOST')
PORT = int(os.getenv('AUTH_SERVICE_PORT'))
ROUTE = os.getenv('AUTH_SERVICE_ROUTE')
SERVICE_NAME = 'auth_service'
SWAGGER_DESCRIPTION = 'RaspberryPi Authentication Service.\n'
SWAGGER_TITLE = 'RaspberryPi Authentication Service'

# AUTHENTICATION CONFIGURATION

ACCESS_TOKEN_SECONDS = int(os.getenv('AUTH_SERVICE_ACCESS_TOKEN_SECONDS'))
REFRESH_TOKEN_SECONDS = int(os.getenv('AUTH_SERVICE_REFRESH_TOKEN_SECONDS'))
SECRET = os.getenv('AUTH_SERVICE_SECRET')

# STORAGE CONFIGURATION

SESSION_STORAGE_PATH = os.getenv('SESSION_STORAGE')
USER_STORAGE_PATH = os.getenv('USER_STORAGE')
