from enum import Enum


class EventCategory(str, Enum):
    PROCESS = 'PROCESS'
    PROCESS_COMMUNICATION = 'PROCESS_COMMUNICATION'
    REMOTE_COMMUNICATION = 'REMOTE_COMMUNICATION'
    SUPERVISOR = 'SUPERVISOR'
    TICK = 'TICK'
    UNKNOWN = 'UNKNOWN'

