from enum import Enum


PROCESS_STATE_PREFIX = 'PROCESS_STATE_'
SUPERVISOR_STATE_CHANGE_PREFIX = 'SUPERVISOR_STATE_CHANGE_'
PROCESS_STATE_PATTERN = f'{PROCESS_STATE_PREFIX}*'
SUPERVISOR_STATE_CHANGE_PATTERN = f'{SUPERVISOR_STATE_CHANGE_PREFIX}*'
TICK_PATTERN = 'TICK_*'


class SupervisorEventName(str, Enum):
    PROCESS_STATE_BACKOFF = 'PROCESS_STATE_BACKOFF'
    PROCESS_STATE_EXITED = 'PROCESS_STATE_EXITED'
    PROCESS_STATE_FATAL = 'PROCESS_STATE_FATAL'
    PROCESS_STATE_RUNNING = 'PROCESS_STATE_RUNNING'
    PROCESS_STATE_STARTING = 'PROCESS_STATE_STARTING'
    PROCESS_STATE_STOPPED = 'PROCESS_STATE_STOPPED'
    PROCESS_STATE_STOPPING = 'PROCESS_STATE_STOPPING'
    SUPERVISOR_STATE_CHANGE_RESTARTING = 'SUPERVISOR_STATE_CHANGE_RESTARTING'
    SUPERVISOR_STATE_CHANGE_RUNNING = 'SUPERVISOR_STATE_CHANGE_RUNNING'
    SUPERVISOR_STATE_CHANGE_SHUTDOWN = 'SUPERVISOR_STATE_CHANGE_SHUTDOWN'
    SUPERVISOR_STATE_CHANGE_STOPPING = 'SUPERVISOR_STATE_CHANGE_STOPPING'
